[build]
     publish = "web/public"
     command = "composer install --no-dev --optimize-autoloader"

[context.production.environment]
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.7.6"
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "https://your-production-domain.com"
